### ISSUE TITLE
Where is release download?

### ISSUE THREAD

**Issue by ghost** [sileshn/SolusWSL#3]
The release section in readme is empty now. I also try to import your image from docker hub using https://github.com/yuk7/wsldl
but I got "[process exited with code 1]" every time I launch solus. Is there any issue with the image so you remove the release section?

**Comment by sileshn** [comment]
Yes, I removed it because it will error after solus updated usysconf. 

https://getsol.us/2020/07/01/usysconf-rewrite-and-major-upgrades-roundup-16/

I have added a new one now. Be warned that it will throw up all kinds of errors when you run update or install any package inside solus because of usysconf update. That can be averted by using a patched usysconf. I cannot unfortunately tell you how to do it.

Read the Readme.md. It has a section on how to build a new zip file. It still works.
